version: "3.9"
services:
  postgres: # Database service
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build: # tell the composer to build the api image
      context: . # specify the directory of the docker file (relevant to this file)
      dockerfile: Dockerfile #specify the name of the docker file
    ports:
      - "8080:8080"
    environment: #this overwrites anything in the app.env
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable # "...@postgres:5432..." this is done, so it uses whatever IP the postgres service is assigned instead of manually specifying it
    depends_on:
      - postgres