package db

import (
	"context"
	"database/sql"
	"fmt"
)

// SQLStore provides all functions to execute db queries and transactions
// For individual queries, we already have the Queries struct in db.go (generated by sqlc)
// each query does 1 operation per table so it doesnt support transactions (COMMIT/ROLLBACK)
// This file will extend its functionality to support Transactions
// by embedding it in the store struct (This is called composition)
// It is the preferred way to extend struct functionality in goLang instead of inheritance
type SQLStore struct {
	*Queries // all individual Query functions provided by `Queries` is available to Store struct
	db       *sql.DB
}

// Store was created to be able to mock the DB for our tests.
// note : we updated sqlc.yaml with `emit_interface: true`, then we ran `make sqlc`
// so we won't have to copy everything that Queries implements into store interface (Check querier.go)
type Store interface {
	Querier
	TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error)
}

// TransferTxParams contains the input parameters of the transfer transaction
type TransferTxParams struct {
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	Amount        int64 `json:"amount"`
}

// TransferTxResult is the result of the transfer transaction
type TransferTxResult struct {
	Transfer    Transfer `json:"transfer"`
	FromAccount Account  `json:"from_account"`
	ToAccount   Account  `json:"to_account"`
	FromEntry   Entry    `json:"from_entry"`
	ToEntry     Entry    `json:"to_entry"`
}

//for deadlock fmt.logs
//var txKey = struct {
//}{}

func NewStore(db *sql.DB) Store {
	return &SQLStore{
		db:      db,
		Queries: New(db), // New was generated by sqlc (creates and returns Queries obj)
	}
}

// execTx executes a function within a database transaction
// starts with lower case e (unexported) because we do not want external packages to call it directly.
// instead, we'll provide an exported function for each specific transaction
func (store *SQLStore) execTx(ctx context.Context, fn func(*Queries) error) error {

	tx, err := store.db.BeginTx(ctx, nil) // &sql.TxOptions{} lets you set isolation level and read only property

	if err != nil {
		return err
	}

	q := New(tx) // this works cuz New accepts Db.tx interface
	err = fn(q)

	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			//if rollback fails
			return fmt.Errorf("tx err: %v, rb error : %v", err, rbErr) // output and return the original err + rollback err
		}
		return err // if rollback successful , return original tx error
	}
	return tx.Commit()
}

func (store *SQLStore) TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error) {
	var result TransferTxResult // create empty result

	err := store.execTx(ctx, func(q *Queries) error {
		var err error

		//we use this mapping for the deadlock fmt.logs belo
		//txName := ctx.Value(txKey)
		//fmt.Println(txName, "Create Transfer")

		result.Transfer, err = q.CreateTransfer(ctx, CreateTransferParams{
			FromAccountID: arg.FromAccountID,
			ToAccountID:   arg.ToAccountID,
			Amount:        arg.Amount,
		})
		if err != nil {
			return err
		}

		//fmt.Println(txName, "Create Entry 1")

		result.FromEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.FromAccountID,
			Amount:    -arg.Amount,
		})
		if err != nil {
			return err
		}

		//fmt.Println(txName, "Create Entry 2")

		result.ToEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.ToAccountID,
			Amount:    arg.Amount,
		})
		if err != nil {
			return err
		}

		// TODO: Update accounts balances (handle Deadlock)

		//Old way (before deadlock handling and addAccountBalance query function), deadlock occurred on get account(for balance)

		//// Account 1

		////fmt.Println(txName, "Get account 1")
		//account1, err := q.GetAccountForUpdate(ctx, arg.FromAccountID)
		//if err != nil {
		//	return err
		//}
		////fmt.Println(txName, "Update account 1")
		//result.FromAccount, err = q.UpdateAccount(ctx, UpdateAccountParams{
		//	ID:      arg.FromAccountID,
		//	Balance: account1.Balance - arg.Amount,
		//})

		//// Account 2
		////fmt.Println(txName, "Get account 2")
		//account2, err := q.GetAccountForUpdate(ctx, arg.ToAccountID)
		//if err != nil {
		//	return err
		//}
		////fmt.Println(txName, "Update account 2")
		//result.ToAccount, err = q.UpdateAccount(ctx, UpdateAccountParams{
		//	ID:      arg.ToAccountID,
		//	Balance: account2.Balance + arg.Amount,
		//})

		// This will also cause deadlock if were transferring acct1 --> acct2 and acct2 --> acct1 concurrently in routines
		//result.FromAccount, err = q.AddAccountBalance(ctx, AddAccountBalanceParams{
		//	ID:     arg.FromAccountID,
		//	Amount: -arg.Amount,
		//})
		//result.ToAccount, err = q.AddAccountBalance(ctx, AddAccountBalanceParams{
		//	ID:     arg.ToAccountID,
		//	Amount: arg.Amount,
		//})

		//to avoid deadlock, we do all updates for each seperately

		//Reason :

		/*
			Account 1 --> Account 2 Transfer
			-W = UPDATE accounts SET balance = balance + 10 WHERE id = 1 RETURNING *;
			-X = UPDATE accounts SET balance = balance - 10 WHERE id = 2 RETURNING *;

		*/

		/* Account 2 --> Account 1 Transfer

		-Y = UPDATE accounts SET balance = balance - 10 WHERE id = 2 RETURNING *;
		-Z = UPDATE accounts SET balance = balance + 10 WHERE id = 1 RETURNING *;

		-W locks Account 1 row
		-Y locks Account 2 row
		-X needs Account 2 row, but it's locked by Y
		-Z needs Account 2 row, but it's locked by X

		So we handle each senders list of transactions at once, all transfers of acct 1 --> acct2 THEN all transfers from account2 --> account1
		*/

		if arg.FromAccountID < arg.ToAccountID {

			result.FromAccount, result.ToAccount, err = addMoney(ctx, q, arg.FromAccountID, -arg.Amount, arg.ToAccountID, arg.Amount)

			if err != nil {
				return err
			}

		} else {

			result.ToAccount, result.FromAccount, err = addMoney(ctx, q, arg.ToAccountID, arg.Amount, arg.FromAccountID, -arg.Amount)

			if err != nil {
				return err
			}
		}

		return nil
	})

	return result, err
}

func addMoney(
	ctx context.Context,
	q *Queries,
	accountID1 int64,
	amount1 int64,
	accountID2 int64,
	amount2 int64,
) (account1 Account, account2 Account, err error) {

	account1, err = q.AddAccountBalance(ctx, AddAccountBalanceParams{
		ID:     accountID1,
		Amount: amount1,
	})

	if err != nil {
		return
	}

	account2, err = q.AddAccountBalance(ctx, AddAccountBalanceParams{
		ID:     accountID2,
		Amount: amount2,
	})

	return
}
